import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="mb-8">
          <nav className="py-4 font-medium">
            <ul className="flex flex-wrap gap-8">
              <li>
                <Link href="/">ZodForm</Link>
              </li>
              <li>
                <Link href="/filters">Filters</Link>
              </li>
              <li>
                <Link href="/filters-with-state">StateFilters</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
